# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.

image: ros:foxy
options:
  docker: true
pipelines:
  # run on pull request only
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - step:
          name: Build and test
          services:
            - docker
          caches:
            - docker
          image:
            name: ros:foxy
            username: $DOCKER_HUB_USERNAME
            password: $DOCKER_HUB_PASSWORD
          script:
            - library_dir=$(pwd)
            - echo $library_dir
            - apt update
            - apt install ros-foxy-xacro
            - source /opt/ros/foxy/setup.bash
            - colcon build

definitions:
  services:
    docker:
      memory: 2048 